name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: 'Hot Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: 'Maintenance'
    label:
      - 'chore'
      - 'refactoring'

change-template: '- $TITLE #$NUMBER (@$AUTHOR)'
change-title-escapes: '\<*_&'
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: 'minor'
template: |
  ## $RESOLVED_VERSION
  put in release summary
  ### Highlights
  ## Detail
  ## Uncategorized
  $CHANGES