# This is a basic workflow to help you get started with Actions

name: E2E Testing

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the develop branch
  push:
    branches:
      - main
      - 'v*'
      - 'feature/*'
      - 'fix/*'
      - 'refactor/*'
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test:
    name: Run E2E Testing
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node_version: ['18']
        os: [ubuntu-latest]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      - name: setup npm info
        uses: actions/setup-node@v4
        with:
          always-auth: true
          node-version: '18'
          registry-url: https://registry.npmjs.org
          scope: 'your-scope-name'
      - name: install package
        run: yarn --frozen-lockfile
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_ACCESS_TOKEN}}
      - name: testing
        uses: cypress-io/github-action@v6
        with:
          install: false
          build: yarn build
          start: yarn start
          wait-on: 'http://localhost:3000'
          wait-on-timeout: 120
          browser: chrome
      - name: review fail testing
        uses: actions/github-script@v7
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const ref = "${{github.ref}}"
            const pull_number = Number(ref.split("/")[2])
            await github.pulls.createReview({
              ...context.repo,
              pull_number,
              body: "E2E test failed!",
              event: "REQUEST_CHANGES"
            })
        if: ${{ failure() && github.event_name == 'pull_request' }}
      - name: review success testing
        uses: actions/github-script@v7
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const ref = "${{github.ref}}"
            const pull_number = Number(ref.split("/")[2])
            await github.pulls.createReview({
              ...context.repo,
              pull_number,
              body: "E2E test passed!",
              event: "APPROVE"
            })
        if: ${{ success() && github.event_name == 'pull_request' }}
